/*
 * Purpose: Persists decision recommendations.
 * Why it exists: Recommendations must be ranked, policy-validated, confidence-scored, and reviewable.
 * Architecture fit: Recommendation child entity generated by the decision intelligence engine.
 */
package com.airural.platform.core.decision.domain;

import jakarta.persistence.*;
import java.util.UUID;

/** JPA entity for recommendations. */
@Entity
@Table(name = "recommendations", schema = "decision")
public class RecommendationEntity {
    @Id private UUID id;
    @Column(nullable = false) private UUID decisionId;
    @Column(nullable = false, length = 180) private String title;
    @Column(nullable = false, columnDefinition = "TEXT") private String description;
    @Column(nullable = false) private Integer priority;
    @Column(nullable = false) private Double impactScore;
    @Column(nullable = false) private Double confidence;
    @Column(nullable = false, columnDefinition = "TEXT") private String costNotes;
    @Column(nullable = false, columnDefinition = "TEXT") private String riskNotes;
    @Column(nullable = false, columnDefinition = "TEXT") private String expectedOutcome;
    @Column(nullable = false) private Boolean humanApprovalRequired;

    protected RecommendationEntity() {}

    public RecommendationEntity(UUID decisionId, String title, String description, Integer priority, Double impactScore, Double confidence, String costNotes, String riskNotes, String expectedOutcome, Boolean humanApprovalRequired) {
        this.id = UUID.randomUUID();
        this.decisionId = decisionId;
        this.title = title;
        this.description = description;
        this.priority = priority;
        this.impactScore = impactScore;
        this.confidence = confidence;
        this.costNotes = costNotes;
        this.riskNotes = riskNotes;
        this.expectedOutcome = expectedOutcome;
        this.humanApprovalRequired = humanApprovalRequired;
    }

    public UUID id() { return id; }
    public String title() { return title; }
    public String description() { return description; }
    public Integer priority() { return priority; }
    public Double impactScore() { return impactScore; }
    public Double confidence() { return confidence; }
    public Boolean humanApprovalRequired() { return humanApprovalRequired; }
}
