/*
 * Purpose: Persists ranked root causes for a decision.
 * Why it exists: Decision outputs need structured, confidence-scored root-cause records.
 * Architecture fit: Root-cause child entity generated by the reasoning pipeline.
 */
package com.airural.platform.core.decision.domain;

import jakarta.persistence.*;
import java.util.UUID;

/** JPA entity for root causes. */
@Entity
@Table(name = "root_causes", schema = "decision")
public class RootCauseEntity {
    @Id private UUID id;
    @Column(nullable = false) private UUID decisionId;
    @Column(nullable = false, length = 180) private String title;
    @Column(nullable = false, columnDefinition = "TEXT") private String description;
    @Column(nullable = false) private Integer rank;
    @Column(nullable = false) private Double confidence;
    @Column(nullable = false, columnDefinition = "TEXT") private String evidenceJson;

    protected RootCauseEntity() {}

    public RootCauseEntity(UUID decisionId, String title, String description, Integer rank, Double confidence, String evidenceJson) {
        this.id = UUID.randomUUID();
        this.decisionId = decisionId;
        this.title = title;
        this.description = description;
        this.rank = rank;
        this.confidence = confidence;
        this.evidenceJson = evidenceJson;
    }

    public UUID id() { return id; }
    public String title() { return title; }
    public String description() { return description; }
    public Integer rank() { return rank; }
    public Double confidence() { return confidence; }
    public String evidenceJson() { return evidenceJson; }
}
